
GET http://localhost:4000

###
 GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNTk3NTA1OH0.SA5RJg4MDZgZUglwNRWnGOK-oFSiGj8dgEkBNiO8Br8
# GET http://localhost:4000

### 
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "username": "khutso",
    "password": "khutsobaloyi"
}

###

POST http://localhost:4000/users/user
Content-Type: application/json

{
    "username": "brandon",
    "password": "ken",
    "store_name": "shoprite"
}

###

GET http://localhost:4000/stores/userstores
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodXRzbyIsInBhc3N3b3JkIjoia2h1dHNvYmFsb3lpIiwiaWF0IjoxNjM2MzY1NzU2fQ.aIHFjJ54v5wBhpH8Z2Vu2b0RT0cU4tv-PHH5TPY9mCE
###

POST http://localhost:4000/stores/addstore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlbiIsInBhc3N3b3JkIjoia2VuIiwiaWF0IjoxNjM1OTg1MTE2fQ.icT4vLAAv_fWv2v5F4ycJao_yawOY3fdjKpWgDZm83M
Content-Type: application/json

{
    "store_id": 3
}

###
GET http://localhost:4000/products/findproduct/6001190111648
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodXRzbyIsInBhc3N3b3JkIjoia2h1dHNvYmFsb3lpIiwiaWF0IjoxNjM3NzU5NDk5fQ.12X8FOM4H15n5u473N_E_Tna7l7uT5ShLG14ABdX6_Y
###
GET http://localhost:4000/products/findstoreproduct?barcode=6001190111648&storeId=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNjExMTE3OH0.quOww5msWmSXMYpcflQSmpk7ftXkoiDaItpGXW-nxYw
###
POST http://localhost:4000/products/addstoreproduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNjEwOTE4Nn0.STqkbOVbPLQ7TMcfrkuqbEQMzP0RSEiEuiWfkYsyqEY
Content-Type: application/json

{
    "product": {
        "store_id": 1,
        "barcode": 6009510808728,
        "price": 26.90
    }
}

###
GET http://localhost:4000/products/storeproducts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtodXRzbyIsInBhc3N3b3JkIjoia2h1dHNvYmFsb3lpIiwiaWF0IjoxNjM2MzY4NTYyfQ.zG_P8szi_m0iGEMK2OQnjfHlmRj3B-0EsyIo8dpdbcw

###
POST http://localhost:4000/products/addproduct
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNjEwOTE4Nn0.STqkbOVbPLQ7TMcfrkuqbEQMzP0RSEiEuiWfkYsyqEY
Content-Type: application/json

{
    "product": {
        "store_id": 2,
        "barcode": 600967881179,
        "name": "popcorn spice",
        "description": "original butter",
        "price": 14.99
    }
}

###
GET http://localhost:4000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNjExMDU1M30.9242JaeWb6k53Ahu0VhTJoDELN5E3V3iQeDXqiVAAa0

###
PATCH http://localhost:4000/products/updateprice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImlhdCI6MTYzNjExMTE3OH0.quOww5msWmSXMYpcflQSmpk7ftXkoiDaItpGXW-nxYw
Content-Type: application/json

{
    "product": {
        "store_id": 1,
        "barcode": 6009510808728,
        "price": 15.99
    }
}
